#!/usr/bin/env node
const process = require('process')
const child_process = require('child_process')
const {ESLint} = require('eslint')

function exec(name) {
  return new Promise(function(resolve){
    child_process.exec(name, resolve)
  })
}

async function lint() {
  const eslint = new ESLint({fix: false})

  await exec('git stash push -k')
  const results = await eslint.lintFiles(['src/**/*.js'])
  await exec('git stash pop')
  
  const formatter = await eslint.loadFormatter('stylish')
  const resultText = formatter.format(results)
  console.log(resultText)

  for (let result of results) {
    if (result.errorCount) {
      process.exitCode = 1
    }
  }
}


lint().catch(err=>{
  process.exitCode = 1
  console.error(err)
})